/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "horizon.stats.index": [],
    "horizon.workload.index": [],
    "horizon.masters.index": [],
    "horizon.monitoring.index": [],
    "horizon.monitoring.store": [],
    "horizon.monitoring-tag.paginate": [
        {
            "name": "tag"
        }
    ],
    "horizon.monitoring-tag.destroy": [
        {
            "name": "tag"
        }
    ],
    "horizon.jobs-metrics.index": [],
    "horizon.jobs-metrics.show": [
        {
            "name": "id"
        }
    ],
    "horizon.queues-metrics.index": [],
    "horizon.queues-metrics.show": [
        {
            "name": "id"
        }
    ],
    "horizon.jobs-batches.index": [],
    "horizon.jobs-batches.show": [
        {
            "name": "id"
        }
    ],
    "horizon.jobs-batches.retry": [
        {
            "name": "id"
        }
    ],
    "horizon.pending-jobs.index": [],
    "horizon.completed-jobs.index": [],
    "horizon.silenced-jobs.index": [],
    "horizon.failed-jobs.index": [],
    "horizon.failed-jobs.show": [
        {
            "name": "id"
        }
    ],
    "horizon.retry-jobs.show": [
        {
            "name": "id"
        }
    ],
    "horizon.jobs.show": [
        {
            "name": "id"
        }
    ],
    "horizon.index": [
        {
            "name": "view"
        }
    ],
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "employee.login": [],
    "employee.login.store": [],
    "employees.create": [],
    "employees.store": [],
    "dashboard": [],
    "employee.togglePushNotifications": [],
    "employee.toggleEmailNotifications": [],
    "employee.logout": [],
    "password.confirm": [],
    "password.check": [],
    "employees.index": [],
    "employees.show": [
        {
            "name": "employee",
            "binding": "username"
        }
    ],
    "employees.edit": [
        {
            "name": "employee",
            "binding": "username"
        }
    ],
    "employees.update": [
        {
            "name": "employee",
            "binding": "username"
        }
    ],
    "employees.destroy": [
        {
            "name": "employee",
            "binding": "username"
        }
    ],
    "employee.tasks": [
        {
            "name": "employee",
            "binding": "username"
        }
    ],
    "tasks.store": [],
    "tasks.update": [
        {
            "name": "task",
            "binding": "id"
        }
    ],
    "tasks.destroy": [
        {
            "name": "task",
            "binding": "id"
        }
    ]
}
}
export {};
