#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

./vendor/bin/sail npm run tsc
./vendor/bin/sail npm run eslint:fix

./vendor/bin/sail pint

./vendor/bin/sail test --coverage --profile
./vendor/bin/sail npm run test:coverage


